affinity: {}
autoscaling:
  enabled: true
  max: 1
  min: 1
  targetCPUUtilizationPercentage: 80
configMap:
  data:
    5432: ef855cef-1a01-4c30-9ba5-2ddef0b1e17b/miha-1722610371:5432
  name: nginx-ingress-tcp-microk8s-conf
  namespace: ingress
env:
  POSTGRES_PASSWORD: password
  POSTGRES_USER: postgres
fullnameOverride: ''
host: 1722610371.miha-clound.com
image:
  repository: mihacloud/1722610371
  tag: latest
imagePullSecrets: []
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  className: nginx
  enabled: true
  hosts:
  - host: 1722610371.miha-clound.com
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  tcpSocket:
    port: 5432
name: miha-1722610371
nameOverride: ''
namespace: ef855cef-1a01-4c30-9ba5-2ddef0b1e17b
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  tcpSocket:
    port: 5432
replicaCount: 1
resources:
  limits:
    cpu: 0.5
    memory: 512Mi
securityContext: {}
service:
  annotations: {}
  port: 5432
  targetPort: 5432
  type: ClusterIP
serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ''
tolerations: []
volumeMounts:
- mountPath: /var/lib/postgresql/data
  name: miha-1722610371-data-volume
volumes:
- name: miha-1722610371-data-volume
  persistentVolumeClaim:
    claimName: miha-1722610371-data-pvc
