namespace: ef855cef-1a01-4c30-9ba5-2ddef0b1e17b
service: s-ef855cef-1a01-4c30-9ba5-2ddef0b1e17b
name: miha-1721754421
image:
    repository: postgres
    tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "" 

serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
    annotations: {}

ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: "db.miha-cloud.com"
        paths:
          - path: /
            pathType: Prefix

livenessProbe:
    tcpSocket:
        port: 5432
    initialDelaySeconds: 30
    periodSeconds: 10

readinessProbe:
    tcpSocket:
        port: 5432
    initialDelaySeconds: 5
    periodSeconds: 10

autoscaling:
    enabled: true
    min: 1
    max: 2
    targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

env: 
    POSTGRES_PASSWORD: "password"
    POSTGRES_USER: "user"
