apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`1722568608.miha-clound.com`)
      services:
        - name: {{ .Values.name }}
          port: {{ .Values.service.port }}
  tls:
    certResolver: letsencrypt
